=== Tecnologias-Web-ISMAI/TCM21-TW-G08/IncendiosFlorestais/XML_XSD_incendios/incendios.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.incendios.org"
 xmlns="http://www.incendios.org"
 elementFormDefault="qualified">
 
 <xs:element name="incendios"  >
  <xs:complexType>
   <xs:sequence>
   <xs:element name="incendio" maxOccurs="unbounded"    >
  <xs:complexType>
   <xs:sequence>
   <xs:element name="pais" type="xs:string" />
   
  
   <xs:element name="local" type="xs:string" />

   
   <xs:element name="ano"  maxOccurs="unbounded" >
    <xs:simpleType>
    <xs:restriction base="xs:integer">
    <xs:minInclusive value="1990" />
    <xs:maxInclusive value="2022" />
    </xs:restriction>
    </xs:simpleType>
   </xs:element>

   <xs:element name="area" type="xs:nonNegativeInteger" minOccurs="0" />
   
  <xs:element name="scie"  maxOccurs="unbounded" >
   <xs:simpleType>
   <xs:restriction base="xs:decimal">
   <xs:minInclusive value="0" />
   <xs:maxInclusive value="1000" />
   </xs:restriction>
   </xs:simpleType>
  </xs:element>
  
  
   </xs:sequence>
   </xs:complexType>
  </xs:element>
   </xs:sequence>
   </xs:complexType>
   </xs:element>
  </xs:schema>

=== Tecnologias-Web-ISMAI/TCM21-TW-G08/IncendiosFlorestais/XML_XSD_incendios/incendios.xml
<?xml version="1.0"?>
<incendios xmlns ="http://www.incendios.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.incendios.org
                             incendios.xsd">
                            
                             <incendio>

                                <pais>Portugal</pais>
                                
                                <local>Seia</local>

                                <ano>2006</ano>
                                
                                <area>600</area>
                                
                                <scie>41.95</scie>
                                
                                </incendio>




                                <incendio>
   
                                   <pais>Portugal</pais>
                                   
                                   <local>Viseu</local>

                                   <ano>2013</ano>
                                   
                                   <area>500</area>
                                   
                                   <scie>90.56</scie>
                                   
                                   </incendio>



                                   
                             <incendio>

                                <pais>Portugal</pais>
                                
                                <local>Madeira</local>

                                <ano>2016</ano>
                                
                                <area>700</area>
                                
                                <scie>100.60</scie>
                                
                                </incendio>



                                
                             <incendio>

                                <pais>Portugal</pais>
                                
                                <local>Pedrog√£o Grande</local>

                                <ano>2017</ano>
                                
                                <area>1000</area>
                                
                                <scie>413.75</scie>
                                
                                </incendio>



                                
                             <incendio>

                                <pais>Portugal</pais>
                                
                                <local>Oliveira do Hospital</local>

                                <ano>2017</ano>
                                
                                <area>600</area>
                                
                                <scie>48.95</scie>
                                
                                </incendio>



                                
                             <incendio>

                                <pais>Portugal</pais>
                                
                                <local>Monchique</local>

                                <ano>2018</ano>
                                
                                <area>300</area>
                                
                                <scie>71.92</scie>
                                
                                </incendio>



                                
                             <incendio>

                                <pais>Portugal</pais>
                                
                                <local>Castro Marim</local>

                                <ano>2021</ano>
                                
                                <area>600</area>
                                
                                <scie>61.05</scie>
                                
                                </incendio>
     
     

</incendios>
